name: build_test
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Install dependencies
        run: |
          sudo apt install -y libgc-dev tmux mc git rsync curl imagemagick
          cargo install mdbook mdbook-mermaid 

      - name: Setup Vlang
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install crystallib
        run: |
          mkdir -p ~/.vmodules/freeflowuniverse
          rm -f ~/.vmodules/freeflowuniverse/crystallib
          ln -s $(pwd)/crystallib ~/.vmodules/freeflowuniverse/crystallib

      - name: Check formatting
        run: |
          v fmt -w .
      
      - name: Run tests
        env:
          VJOBS: 1
          OFFLINE: 1
        run: |
          v -enable-globals -stats test crystallib/algo
          v -enable-globals -stats test crystallib/baobab
          v -enable-globals -stats test crystallib/biz
          v -enable-globals -stats test crystallib/builder
          v -enable-globals -stats test crystallib/clients
          v -enable-globals -stats test crystallib/core
          v -enable-globals -stats test crystallib/crypt
          v -enable-globals -stats test crystallib/data
          v -enable-globals -stats test crystallib/installers
          v -enable-globals -stats test crystallib/osal
          v -enable-globals -stats test crystallib/servers
          v -enable-globals -stats test crystallib/threefold
          v -enable-globals -stats test crystallib/tools
          v -enable-globals -stats test crystallib/ui
          v -enable-globals -stats test crystallib/web

