vmType: qemu
os: null
arch: null
images:
- location: "https://cloud-images.ubuntu.com/releases/24.04/release-20240806/ubuntu-24.04-server-cloudimg-amd64.img"
  arch: "x86_64"
- location: "https://cloud-images.ubuntu.com/releases/24.04/release-20240806/ubuntu-24.04-server-cloudimg-arm64.img"
  arch: "aarch64"
# - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
#   arch: "x86_64"
# - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
#   arch: "aarch64"
cpus: 8
memory: null
disk: null
mounts:
- location: "~"
  mountPoint: null
  writable: null
  sshfs:
    cache: null
    followSymlinks: true
    sftpDriver: null
- location: "/tmp/lima"
  writable: true
- location: "~/code"
  mountPoint: "/code"
  writable: true  
#mountType: virtiofs
mountInotify: null
ssh:
  localPort: 0
  loadDotSSHPubKeys: null
  forwardAgent: null
  forwardX11: null
  forwardX11Trusted: null
provision:
- mode: system
  script: |
    #!/bin/bash
    set -eux -o pipefail
    mkdir -p /aptcache
    chmod -R 777 /aptcache
    export DEBIAN_FRONTEND=noninteractive
    apt update 
    apt-get install -y mc curl -y
- mode: user
  script: |
    #!/bin/bash
    set -eux -o pipefail
